### ISSUE TITLE
Shop - single entry

### ISSUE THREAD

**Issue by CiaranChris** [briggySmalls/skin-deep-server#101]

**Comment by CiaranChris** [comment]
![sd_shop_single](https://user-images.githubusercontent.com/29028655/49041623-996d7300-f1bd-11e8-8d3c-8eaff0c332a3.jpg)

Perhaps there are a few things, related products, product gallery could be saved for the V2

**Comment by briggySmalls** [comment]
V1 mostly done, but I'd like another crack at getting related posts to appear. I'm not sure why they are not...

**Comment by briggySmalls** [comment]
OK. it looks like there need to be at least 10 posts for related posts to work.

We have _exactly_ 10 product posts. Where not all of them are in the same category.

So it is possible it will start working soon (Movements was only recently added). Otherwise it will be a matter of time, waiting for more products to be release.

**Comment by briggySmalls** [comment]
Have a look @CiaranChris

**Comment by CiaranChris** [comment]
Thank you. I'm really into this. What are your thoughts?
