### ISSUE TITLE
Style videos distinctly

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#18]
Posts of a video format could be styled differently - e.g. have a dark background

**Comment by briggySmalls** [comment]
Sylvia suggested we display a gif of the videos whenever the featured image would be displayed in order to convey a sense of interactivity.

**Comment by CiaranChris** [comment]
What would you think if we were to apply a dark background to all video content on the site.

So the videos page itself would display with a dark background, still show on a grid, then the pages would be as they are? 

The only thing would be the we would need some sort of code to switch the logo from black to white when going from this light background to dark. 

currently the logo stays black but i think its because thats the only image were using atm

![screen shot 2018-11-05 at 21 29 02](https://user-images.githubusercontent.com/29028655/48029518-45cfb280-e146-11e8-9f93-5c0d5ce06fe0.png)

**Comment by briggySmalls** [comment]
I'm not sure I follow. Do you mean you'd want the 'videos' archive grid to be displayed in dark too. This one:
<img width="1433" alt="screen shot 2018-11-05 at 22 46 49" src="https://user-images.githubusercontent.com/11054133/48031622-c1346280-e14c-11e8-8396-d4202d946d8c.png">

Yes, it would require a small update but it would be possible to supply two images: light and dark, for the site logo. So I can look into that while you make the two images?

**Comment by briggySmalls** [comment]
Would it be possible to add the same, time, date, location to the specific events themselves, under the headline? maybe next to 'F see event on FB'

**Comment by briggySmalls** [comment]
@ciaranchris, still need clarification on this

**Comment by briggySmalls** [comment]
Also, giphy offer a service to create GIFs from Vimeo videos. So we might be able to revisit styling videos on an archive in this way

**Comment by CiaranChris** [comment]
![screen shot 2018-11-28 at 14 41 14](https://user-images.githubusercontent.com/29028655/49159857-562a1600-f31d-11e8-8852-164b58267aa5.png)

Could we lose the card colour?

**Comment by briggySmalls** [comment]
yh
