### ISSUE TITLE
Restyle title

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#79]
Anu has asked for the title of a page to be removed on some pages. e.g. [Category - Art](http://skindeepmag.tk/category/art/).

We can do this, of course, although it should probably be there but invisible for screen readers/accessibility.

**Comment by briggySmalls** [comment]
I think it is better to keep the title. It helps a user navigate (confirms expectations) and also makes the link appropriate for sharing. Jacobin and Vice both keep it.

Anu is on board but thinks it should be restyled to look more like an intentional heading rather than a "mistake". Note: on the 'Back to basics' category, the category name is displayed in 4 different places, which should be reduced.

**Comment by CiaranChris** [comment]
I think we may have to either remove (make invisible) or add more spacing so that the submenu and the page title aren't so close, though i'm leaning more towards remove as the sub menu is there whilst browsing the page and is highlighted in a different colour when the page is selected.

it works for Jacobin and Dazed as they have no sticky menu bar at the top of the screen. 

In the case of back to basics, editorial would have to come up with a new title for the articles rather than it being repeated by both the category and title. Here is where I would probably agree with Anu and 'remove' the page title.

**Comment by briggySmalls** [comment]
Yeah. For sure the category name (Back to basics) shouldn't be in the article title. That is a hangover from the old design. Once removed that makes the title shown in 3 places (menu, heading, and category of each post in grid).

[This question](https://ux.stackexchange.com/questions/54733/should-i-have-a-heading-on-every-page) conveys kind of how I feel: it is good for navigation/clarity to have the heading present. Plus on mobile you won't see the menu items to highlight it.

**Comment by briggySmalls** [comment]
Anu has requested for this to be removed again. Twice, in fact:

> Do you need Articles in top left hand corner above slider, underneath logo? Can we get rid of this?

and 

> we’ve chatted abotu this, but the back to basics needs to be removed from teh title of the pieces otherwise you’re repeating the phrase like a billion times in one page!

**Comment by briggySmalls** [comment]
Closing as fixed, as I'm tracking the editorial change in another issue
